version: '3'

services:
  tests:
    build: .
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=testdb
      - MONGO_COLLECTION=testcollection
      - MONGO_USER=root
      - MONGO_PASSWORD=password
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
